gazebo:
  delay: 0.009
  contacts: [ "LF_FOOT", "LH_FOOT", "RF_FOOT", "RH_FOOT" ]
  imus:
    unitree_imu:
      frame_id: unitree_imu
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
      
gazebo_ros_control:
  pid_gains:
    
    #for mimic joint (does not work due to hardware interface being used by WBC)
    RF_ankle: {p: 5, i: 0, d: 0.5, i_clamp: 50, antiwindup: false, publish_state: false}
    LF_ankle: {p: 5, i: 0, d: 0.5, i_clamp: 50, antiwindup: false, publish_state: false}
    RH_ankle: {p: 5, i: 0, d: 0.5, i_clamp: 50, antiwindup: false, publish_state: false}
    LH_ankle: {p: 5, i: 0, d: 0.5, i_clamp: 50, antiwindup: false, publish_state: false}
